[program:m33-standard-client-XX]
command=python /opt/M33-Lotto-Bot-Standard/src/app/main.py --config-dir /opt/M33-Lotto-Bot-Standard/configs/client_XX
directory=/opt/M33-Lotto-Bot-Standard
user=www-data
autostart=false
autorestart=true
startsecs=10
stopwaitsecs=30
stdout_logfile=/var/log/m33-standard/client_XX/stdout.log
stderr_logfile=/var/log/m33-standard/client_XX/stderr.log
environment=PYTHONPATH="/opt/M33-Lotto-Bot-Standard",HOME="/tmp",TZ="Asia/Ho_Chi_Minh"
priority=999
stopsignal=TERM
stopwaitsecs=30
killasgroup=true
stopasgroup=true